# Five-class score prediction with TF-IDF and E5

Train three score classifiers: L2-regularized logistic classification, kNN,
and XGBoost. Compare **TF-IDF** and frozen **E5 with four extra features
(388 dimensions)**. Each question has a score distribution for each of the
11 candidate LLMs over the fixed values **0, 0.25, 0.5, 0.75 and 1**.

Read each distribution in two ways:

- **Hard class:** the score with the highest predicted probability.
- **Expected score:** the probability-weighted average of the five scores.

Both outputs share the same predicted dollar cost. The experiment uses train,
calibration and validation. Training-only cross-validation selects the logistic
regularization strength. Calibration predictions are saved for later work;
no calibrator is fitted here. Validation evaluates the resulting predictions.

## 1. Environment and paths

Use a Python environment with NumPy, pandas, SciPy, scikit-learn >= 1.6,
XGBoost >= 2.0, joblib, IPython and Jinja2. The prepared preprocessing objects
should be used with compatible package versions.

Keep the prepared files in this layout:

```text
project/
  data/processed/
    char_tfidf_50k/
    multilingual_e5_small_chunk480/
  2_Router_Training/
    TF-IDF_E5_Score_Classification_Router.ipynb
```

A layout with `1_data_preparation/data/processed/` is also supported. The code
searches the current working directory and its parents. If the data lives
elsewhere, set `DATA_PREPARATION_DIR` to the folder containing `data/`, or set
the `ERDOS_DATA_DIR` environment variable. No user-specific paths are required.
Copy the prepared data with the notebook, or run the project's data-preparation
steps before using this file.

`RUN_MODE="full"` uses all prepared rows. `"smoke"` runs a small execution check;
its metrics are not a performance estimate. Each run gets a new output folder.

In [1]:
from pathlib import Path
from datetime import datetime, timezone
from time import perf_counter
import inspect
import json
import os
import warnings

import joblib
import numpy as np
import pandas as pd
import sklearn
import xgboost
from IPython.display import display
from scipy.sparse import load_npz
from sklearn.base import clone
from sklearn.exceptions import ConvergenceWarning
from sklearn.linear_model import LogisticRegression, Ridge
from sklearn.model_selection import GroupKFold
from sklearn.neighbors import NearestNeighbors
from xgboost import XGBClassifier, XGBRegressor

In [2]:
RUN_MODE = "full"
DATA_PREPARATION_DIR = None  # Optional: folder containing data/.
OUTPUT_BASE_OVERRIDE = None  # Optional: output folder outside the project.
SEED = 42
SPLITS = ("train", "calibration", "validation")
SMOKE_LIMITS = {"train": 512, "calibration": 128, "validation": 256}

score_support = np.array([0.0, 0.25, 0.5, 0.75, 1.0])
K_VALUES = [1, 2, 3, 5, 10, 20, 40]
DISPLAY_K = 40
QUERY_BATCH_SIZE = 128

LINEAR_C_GRID = np.array([0.1, 1.0, 10.0])
LINEAR_MAX_ITER = 300
LINEAR_RETRY_MAX_ITER = (1000, 2000)
LINEAR_TOL = 1e-3
COST_RIDGE_ALPHA = {"tfidf": 10.0, "e5_388": 1.0}

XGB_DEVICE = "cpu"  # Set to "cuda" with a supported GPU installation.
XGB_N_JOBS = 4
XGB_ROUNDS = 10 if RUN_MODE == "smoke" else 100

if RUN_MODE not in {"smoke", "full"}:
    raise ValueError("RUN_MODE must be 'smoke' or 'full'.")
if XGB_DEVICE not in {"cpu", "cuda"}:
    raise ValueError("XGB_DEVICE must be 'cpu' or 'cuda'.")
if DISPLAY_K not in K_VALUES:
    raise ValueError("DISPLAY_K must be in K_VALUES.")


def resolve_preparation_dir(override=None):
    """Find a prepared-data folder, preferring the closest project root."""
    requested = override or os.environ.get("ERDOS_DATA_DIR")
    if requested:
        candidates = [Path(requested).expanduser().resolve()]
    else:
        working_dir = Path.cwd().resolve()
        candidates = [
            candidate
            for parent in (working_dir, *working_dir.parents)
            for candidate in (parent, parent / "1_data_preparation")
        ]
    required = (
        Path("data/processed/char_tfidf_50k/preprocessing.joblib"),
        Path("data/processed/multilingual_e5_small_chunk480/embedding_metadata.json"),
    )
    for candidate in dict.fromkeys(candidates):
        if all((candidate / relative).is_file() for relative in required):
            return candidate.resolve()
    raise FileNotFoundError(
        "Prepared TF-IDF and E5 files were not found. Set DATA_PREPARATION_DIR "
        "or ERDOS_DATA_DIR to the folder containing data/processed/."
    )


preparation_dir = resolve_preparation_dir(DATA_PREPARATION_DIR)
table_dir = preparation_dir / "data/processed/char_tfidf_50k"
e5_dir = preparation_dir / "data/processed/multilingual_e5_small_chunk480"
project_dir = preparation_dir.parent if preparation_dir.name == "1_data_preparation" else preparation_dir
output_base = (
    Path(OUTPUT_BASE_OVERRIDE).expanduser().resolve()
    if OUTPUT_BASE_OVERRIDE is not None
    else project_dir / "2_Router_Training/experiment_outputs/score_classification_5class"
)
run_stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S_%fZ")
run_dir = output_base / f"{RUN_MODE}_seed{SEED}_{run_stamp}"
run_dir.mkdir(parents=True, exist_ok=False)
print("Mode:", RUN_MODE)
print("Prepared data:", preparation_dir)
print("Outputs:", run_dir)

Mode: full
Prepared data: C:\Users\johnh\MachineLearning\project_erdos
Outputs: C:\Users\johnh\MachineLearning\project_erdos\2_Router_Training\experiment_outputs\score_classification_5class\full_seed42_20261013T080041_062763Z

## 2. Load the prepared inputs

Reuse the question, score and dollar-cost tables, pure TF-IDF features, and
388-dimensional E5 features. Row indices and LLM column order must agree.
The original score tables stay unchanged throughout this notebook.

In [3]:
preprocessing = joblib.load(table_dir / "preprocessing.joblib")
tfidf_vectorizer_50k = preprocessing["tfidf_vectorizer"]
model_names = list(preprocessing["model_names"])
assert len(model_names) == 11
n_tfidf_features = len(tfidf_vectorizer_50k.vocabulary_)
e5_length_scaler = joblib.load(e5_dir / "length_scaler.joblib")
e5_count_scaler = joblib.load(e5_dir / "count_scaler.joblib")
feature_labels = {"tfidf": "TF-IDF", "e5_388": "E5 + features (388)"}
full_tables, full_features = {}, {feature: {} for feature in feature_labels}
for split in SPLITS:
    full_tables[split] = {name: pd.read_pickle(table_dir / f"{split}_{name}.pkl")
                         for name in ("questions", "scores", "costs")}
    q, s, c = (full_tables[split][name] for name in ("questions", "scores", "costs"))
    assert q.index.is_unique and q.index.equals(s.index) and q.index.equals(c.index)
    assert s.columns.tolist() == c.columns.tolist() == model_names
    assert np.isfinite(s.to_numpy(dtype=float)).all() and s.ge(0).all().all() and s.le(1).all().all()
    assert np.isfinite(c.to_numpy(dtype=float)).all() and c.gt(0).all().all()
    full_features["tfidf"][split] = load_npz(table_dir / f"X_{split}.npz")[:, :n_tfidf_features].astype(np.float32).tocsr()
    full_features["e5_388"][split] = np.load(e5_dir / f"X_{split}_e5_full_features.npy", allow_pickle=False)
    assert full_features["tfidf"][split].shape == (len(q), n_tfidf_features)
    assert full_features["e5_388"][split].shape == (len(q), 388)

# Keep the full tables for label coverage; only the execution subset changes.
tables, split_features = {}, {feature: {} for feature in feature_labels}
for split in SPLITS:
    q = full_tables[split]["questions"]
    positions = np.arange(len(q))
    if RUN_MODE == "smoke":
        rng = np.random.default_rng(SEED + SPLITS.index(split))
        positions = rng.choice(len(q), min(SMOKE_LIMITS[split], len(q)), replace=False)
        if split == "train":
            # Include each observed score to exercise the fixed mapping in smoke mode.
            scores = full_tables[split]["scores"].to_numpy(dtype=float)
            examples = [np.argwhere(scores == value)[0, 0] for value in np.unique(scores)]
            positions = np.unique(np.r_[positions, examples])
        positions.sort()
    tables[split] = {name: frame.iloc[positions].copy() for name, frame in full_tables[split].items()}
    for feature in feature_labels:
        split_features[feature][split] = full_features[feature][split][positions].copy()
    tables[split]["questions"][["sample_id"]].to_csv(run_dir / f"{split}_rows.csv")
train_questions, train_scores, train_costs = (tables["train"][name] for name in ("questions", "scores", "costs"))
validation_scores, validation_costs = (tables["validation"][name] for name in ("scores", "costs"))
train_scores_arr = train_scores.to_numpy(dtype=float)  # Original recorded scores.
cost_means = train_costs.to_numpy(dtype=float).mean(axis=0)
train_cost_normalized = (train_costs.to_numpy(dtype=float) / cost_means).astype(np.float32)
train_groups = train_questions["question_group"].to_numpy()
assert len(train_questions) >= max(K_VALUES)
all_questions = pd.concat([tables[split]["questions"].assign(_split=split) for split in SPLITS])
assert all_questions["sample_id"].is_unique
for group_key in ("question_group", "question_text"):
    assert all_questions.groupby(group_key)["_split"].nunique().eq(1).all()
display(pd.DataFrame({"Questions": {split: len(tables[split]["questions"]) for split in SPLITS}}))
print("Fixed score classes:", score_support.tolist())

C:\Users\johnh\Documents\Codex\2026-09-25\https-arxiv-org-abs-2406-18665\work\knn_verify_deps\sklearn\base.py:442: InconsistentVersionWarning: Trying to unpickle estimator TfidfTransformer from version 1.9.0 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
C:\Users\johnh\Documents\Codex\2026-09-25\https-arxiv-org-abs-2406-18665\work\knn_verify_deps\sklearn\base.py:442: InconsistentVersionWarning: Trying to unpickle estimator TfidfVectorizer from version 1.9.0 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
C:\Users\johnh\Documents\Codex\2026-09-25\https-arxiv-org-abs-2406-18665\work\knn_verify_deps\sklearn\base.py:442: InconsistentVersionWarning: Trying to unpickle estimator StandardScaler from version 1.9.0 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

             Questions
train            21900
calibration       3648
validation        3649

Fixed score classes: [0.0, 0.25, 0.5, 0.75, 1.0]

## 3. Why five score classes?

The five anchors cover **99.858% of training scores**. The table below counts
individual question-LLM scores in the prepared files, before any mapping or
smoke subsetting. The other values are sparse and provide little support for
learning separate classes.

| Recorded score | Train count | Calibration count | Validation count |
|---|---:|---:|---:|
| 0 | 93,268 | 15,532 | 15,346 |
| 0.25 | 15,064 | 2,417 | 2,418 |
| 0.5 | 8,075 | 1,304 | 1,382 |
| 0.75 | 27,679 | 4,599 | 4,561 |
| 1 | 96,473 | 16,203 | 16,386 |
| Other values | 341 | 73 | 46 |
| **Five-anchor coverage** | **99.858%** | **99.818%** | **99.885%** |

Using five classes gives a compact common output schema and reduces the number
of sparsely supported categories. It is a practical simplification; it does not
guarantee higher predictive accuracy or resolve uncertainty in the grading.
The next cell recomputes this table from the files loaded on your computer.

For classification, map each recorded score $s$ to its nearest fixed anchor:

$$z(s)=\arg\min_{j\in\{0,\ldots,4\}}|s-a_j|,
\qquad a=(0,\,0.25,\,0.5,\,0.75,\,1).$$

An exact midpoint uses the lower anchor. Current non-anchor values map as follows:

| Recorded values | Classification target |
|---|---:|
| 0.1 | 0 |
| 0.2, 0.3 | 0.25 |
| 0.4, 0.6 | 0.5 |
| 0.7, 0.8 | 0.75 |
| 0.9 | 1 |

The anchors and rule are fixed before evaluation. All questions remain in the
experiment. Classification accuracy uses mapped targets. MSE, MAE and WAPE use
the **original recorded scores**, so their meaning is preserved.

In [4]:
coverage_rows = []
for label in [*score_support, "Other values"]:
    row = {"Recorded score": label}
    for split in SPLITS:
        values = full_tables[split]["scores"].to_numpy(dtype=float)
        row[split] = int(
            (~np.isin(values, score_support)).sum()
            if isinstance(label, str) else (values == label).sum()
        )
    coverage_rows.append(row)
label_coverage_counts = pd.DataFrame(coverage_rows).set_index("Recorded score")
anchor_coverage = pd.DataFrame({
    split: {
        "Total score entries": full_tables[split]["scores"].size,
        "Five-anchor coverage": np.isin(
            full_tables[split]["scores"].to_numpy(dtype=float), score_support,
        ).mean(),
    }
    for split in SPLITS
}).T
display(label_coverage_counts)
display(anchor_coverage.style.format({
    "Total score entries": "{:,.0f}", "Five-anchor coverage": "{:.3%}",
}))
label_coverage_counts.to_csv(run_dir / "raw_score_value_counts.csv")
anchor_coverage.to_csv(run_dir / "raw_score_anchor_coverage.csv")

                train  calibration  validation
Recorded score
0.0             93268        15532       15346
0.25            15064         2417        2418
0.5              8075         1304        1382
0.75            27679         4599        4561
1.0             96473        16203       16386
Other values      341           73          46

In [5]:
def encode_score_classes(values):
    """Map original scores to fixed anchors without changing the source array."""
    values = np.asarray(values, dtype=float)
    if not np.isfinite(values).all() or np.any((values < 0) | (values > 1)):
        raise ValueError("Scores must be finite and lie in [0, 1].")
    distances = np.abs(values[..., None] - score_support)
    return distances.argmin(axis=-1).astype(np.int64)


def align_class_probabilities(probabilities, classes, n_classes):
    probabilities = np.asarray(probabilities, dtype=float)
    classes = np.asarray(classes, dtype=int)
    aligned = np.zeros((len(probabilities), n_classes), dtype=float)
    aligned[:, classes] = probabilities
    if not np.isfinite(aligned).all() or np.any(aligned < 0) or not np.allclose(aligned.sum(axis=1), 1, atol=1e-6):
        raise ValueError("Invalid score probability distribution.")
    return aligned


def class_log_loss(targets, probabilities, floor=1e-12):
    true_probability = probabilities[np.arange(len(targets)), targets]
    return float(-np.log(np.maximum(true_probability, floor)).mean())


def prediction_frame(values, split):
    return pd.DataFrame(values, index=tables[split]["questions"].index, columns=model_names)


score_class_ids = encode_score_classes(train_scores_arr)
training_folds = list(GroupKFold(n_splits=3, shuffle=True, random_state=SEED).split(
    train_scores_arr, groups=train_groups,
))
for fit_indices, heldout_indices in training_folds:
    assert not np.intersect1d(train_groups[fit_indices], train_groups[heldout_indices]).size
e5_train = split_features["e5_388"]["train"]
raw_lengths = e5_length_scaler.inverse_transform(e5_train[:, 384:385])
raw_counts = e5_count_scaler.inverse_transform(e5_train[:, 385:387])
training_texts = train_questions["question_text"].to_numpy()


def build_fold_features(feature, fit_indices, heldout_indices):
    if feature == "tfidf":
        vectorizer = clone(tfidf_vectorizer_50k)
        return (
            vectorizer.fit_transform(training_texts[fit_indices]).astype(np.float32).tocsr(),
            vectorizer.transform(training_texts[heldout_indices]).astype(np.float32).tocsr(),
        )
    length_scaler = clone(e5_length_scaler).fit(raw_lengths[fit_indices])
    count_scaler = clone(e5_count_scaler).fit(raw_counts[fit_indices])

    def transform(positions):
        return np.column_stack([e5_train[positions, :384],
                                length_scaler.transform(raw_lengths[positions]),
                                count_scaler.transform(raw_counts[positions]),
                                e5_train[positions, 387:388]]).astype(np.float32)

    return transform(fit_indices), transform(heldout_indices)


prediction_bundles = {}

## 4. L2-regularized logistic classification

Train one classifier per candidate LLM. Each classifier produces probabilities
for the five anchors. Cross-entropy rewards probability assigned to the correct
mapped class, and L2 regularization controls coefficient size:

$$\mathcal L_{\mathrm{score}}=
-\frac1n\sum_{i=1}^n\log p_{i,z_i}
+\frac\lambda2\|W\|_F^2.$$

In scikit-learn, a smaller `C` means stronger regularization. Select one `C` per
feature set by mean cross-entropy over three training folds and the 11 LLMs.
Question groups stay within one fold. TF-IDF and the extra-feature scalers are
refitted inside each fold; the frozen E5 vectors are reused.

The price head is a multi-output Ridge model. For LLM $m$, let
$\mu_m=\operatorname{mean}_{\mathrm{train}}c_{im}$. Fit normalized costs
$c_{im}/\mu_m$ with a squared-error objective and L2 penalty. Clip negative
estimates to a small positive value and multiply by $\mu_m$ to restore dollars.

In [6]:
L2_OPTIONS = {"penalty": "l2"} if inspect.signature(LogisticRegression).parameters["l1_ratio"].default is None else {"l1_ratio": 0.0}


def fit_linear_score_head(features, targets, C):
    """Return a classifier, or its constant class, with fit diagnostics."""
    classes = np.unique(targets)
    if classes.size == 1:
        return {
            "classifier": None, "constant_class": int(classes[0]),
            "iterations": 0, "converged": True, "observed_classes": classes,
            "convergence_warning_count": 0,
        }
    classifier = LogisticRegression(
        C=float(C), solver="lbfgs", max_iter=LINEAR_MAX_ITER, **L2_OPTIONS,
        tol=LINEAR_TOL, random_state=SEED,
    )
    total_iterations, warning_count = 0, 0
    for iteration_limit in (LINEAR_MAX_ITER, *LINEAR_RETRY_MAX_ITER):
        classifier.set_params(max_iter=iteration_limit)
        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter("always", ConvergenceWarning)
            classifier.fit(features, targets)
        convergence_messages = [str(item.message) for item in caught
                                if issubclass(item.category, ConvergenceWarning)]
        warning_count += len(convergence_messages)
        total_iterations += int(classifier.n_iter_.max())
        for item in caught:
            if not issubclass(item.category, ConvergenceWarning):
                warnings.warn(str(item.message), item.category)
        if not convergence_messages:
            break
        # Continue from the current coefficients with the same objective and tolerance.
        classifier.set_params(warm_start=True)
        print(f"    iteration limit {iteration_limit}: continuing optimization", flush=True)
    if not np.isfinite(classifier.coef_).all() or not np.isfinite(classifier.intercept_).all():
        raise ValueError("A linear score classifier produced nonfinite parameters.")
    return {
        "classifier": classifier, "constant_class": None,
        "iterations": total_iterations,
        "converged": not convergence_messages,
        "observed_classes": classifier.classes_.astype(int),
        "convergence_warning_count": warning_count,
    }


def linear_score_probabilities(head, features):
    if head["classifier"] is None:
        probabilities = np.zeros((features.shape[0], len(score_support)))
        probabilities[:, head["constant_class"]] = 1.0
        return probabilities
    classifier = head["classifier"]
    return align_class_probabilities(
        classifier.predict_proba(features), classifier.classes_,
        len(score_support),
    )

In [7]:
linear_cv_rows = []
for feature in feature_labels:
    for fold_id, (fit_indices, heldout_indices) in enumerate(training_folds, 1):
        print(f"Linear score CV / {feature_labels[feature]} / fold {fold_id}: features", flush=True)
        X_fit, X_heldout = build_fold_features(feature, fit_indices, heldout_indices)
        for C in LINEAR_C_GRID:
            started = perf_counter()
            losses = []
            unseen_labels = 0
            n_unconverged = 0
            warning_count = 0
            max_iterations = 0
            max_observed_classes = 0
            for model_position, model_name in enumerate(model_names):
                head = fit_linear_score_head(
                    X_fit, score_class_ids[fit_indices, model_position], C,
                )
                probabilities = linear_score_probabilities(head, X_heldout)
                targets = score_class_ids[heldout_indices, model_position]
                losses.append(class_log_loss(targets, probabilities))
                unseen_labels += int((~np.isin(targets, head["observed_classes"])).sum())
                n_unconverged += int(not head["converged"])
                warning_count += head["convergence_warning_count"]
                max_iterations = max(max_iterations, head["iterations"])
                max_observed_classes = max(max_observed_classes, len(head["observed_classes"]))
                print(
                    f"  C={C:g} / {model_position + 1}/{len(model_names)} / "
                    f"{model_name}: CE={losses[-1]:.4f}, "
                    f"iterations={head['iterations']}, converged={head['converged']}",
                    flush=True,
                )
            linear_cv_rows.append({
                "Feature": feature, "Fold": fold_id, "C": float(C),
                "Questions": len(heldout_indices), "Mean_CrossEntropy": np.mean(losses),
                "Unseen_label_events": unseen_labels,
                "Unconverged_heads": n_unconverged, "Max_iterations": max_iterations,
                "Convergence_warnings": warning_count, "Max_observed_classes": max_observed_classes,
                "Seconds": perf_counter() - started,
            })
        del X_fit, X_heldout

linear_cv_table = pd.DataFrame(linear_cv_rows)
linear_cv_summary_rows = []
for (feature, C), rows in linear_cv_table.groupby(["Feature", "C"], sort=False):
    linear_cv_summary_rows.append({
        "Feature": feature, "C": C,
        "CV_CrossEntropy": np.average(rows["Mean_CrossEntropy"], weights=rows["Questions"]),
        "Unseen_label_events": int(rows["Unseen_label_events"].sum()),
        "Unconverged_heads": int(rows["Unconverged_heads"].sum()),
        "Convergence_warnings": int(rows["Convergence_warnings"].sum()),
        "Max_iterations": int(rows["Max_iterations"].max()),
        "Max_observed_classes": int(rows["Max_observed_classes"].max()),
        "Seconds": rows["Seconds"].sum(),
    })
linear_cv_summary = pd.DataFrame(linear_cv_summary_rows)
selected_linear_C = {}
for feature in feature_labels:
    choices = linear_cv_summary.loc[linear_cv_summary["Feature"] == feature]
    # Exact ties favor the smaller C, which gives stronger regularization.
    best = choices.sort_values(["CV_CrossEntropy", "C"], kind="stable").iloc[0]
    selected_linear_C[feature] = float(best["C"])
display(linear_cv_summary)
print("Selected score-classifier C:", selected_linear_C)
if linear_cv_summary["Unconverged_heads"].sum():
    warnings.warn("Some CV fits reached the iteration limit; increase LINEAR_MAX_ITER before interpreting close results.")

Linear score CV / TF-IDF / fold 1: features
Parallel linear: 33 tasks, 3 processes
Completed 1/33: {'model_position': 2, 'seconds': 8.72942000022158, 'fits': [{'kind': 'linear', 'C': 0.1, 'converged': True, 'iterations': 25, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold1_m2_C0.1.joblib'}]}
Completed 2/33: {'model_position': 1, 'seconds': 9.478393900208175, 'fits': [{'kind': 'linear', 'C': 0.1, 'converged': True, 'iterations': 27, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold1_m1_C0.1.joblib'}]}
Completed 3/33: {'model_position': 0, 'seconds': 9.714522399939597, 'fits': [{'kind': 'linear', 'C': 0.1, 'converged': True, 'iterations': 24, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold1_m0_C0.1.joblib'}]}
Completed 4/33: {'model_position': 5, 'seconds': 6.2953893998637795, 'fits': [{'kind': 'linear', 'C': 0.1, 'converged': True, 'iterations': 16, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold1_m5_C0.1.joblib'}]}
Completed 5/33: {'model_position': 3, 'seconds': 7.463491200003773, 'fits': [{'kind': 'linear', 'C': 0.1, 'converged': True, 'iterations': 21, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold1_m3_C0.1.joblib'}]}
Completed 6/33: {'model_position': 4, 'seconds': 11.379446000326425, 'fits': [{'kind': 'linear', 'C': 0.1, 'converged': True, 'iterations': 31, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold1_m4_C0.1.joblib'}]}
Completed 7/33: {'model_position': 6, 'seconds': 7.22096210019663, 'fits': [{'kind': 'linear', 'C': 0.1, 'converged': True, 'iterations': 19, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold1_m6_C0.1.joblib'}]}
Completed 8/33: {'model_position': 7, 'seconds': 8.145114399958402, 'fits': [{'kind': 'linear', 'C': 0.1, 'converged': True, 'iterations': 20, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold1_m7_C0.1.joblib'}]}
Completed 9/33: {'model_position': 8, 'seconds': 8.638348400127143, 'fits': [{'kind': 'linear', 'C': 0.1, 'converged': True, 'iterations': 20, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold1_m8_C0.1.joblib'}]}
Completed 10/33: {'model_position': 10, 'seconds': 9.422000900376588, 'fits': [{'kind': 'linear', 'C': 0.1, 'converged': True, 'iterations': 22, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold1_m10_C0.1.joblib'}]}
Completed 11/33: {'model_position': 9, 'seconds': 12.475957400165498, 'fits': [{'kind': 'linear', 'C': 0.1, 'converged': True, 'iterations': 32, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold1_m9_C0.1.joblib'}]}
Completed 12/33: {'model_position': 1, 'seconds': 15.73490669997409, 'fits': [{'kind': 'linear', 'C': 1.0, 'converged': True, 'iterations': 34, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold1_m1_C1.joblib'}]}
Completed 13/33: {'model_position': 2, 'seconds': 18.1476397998631, 'fits': [{'kind': 'linear', 'C': 1.0, 'converged': True, 'iterations': 37, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold1_m2_C1.joblib'}]}
Completed 14/33: {'model_position': 0, 'seconds': 25.59489030018449, 'fits': [{'kind': 'linear', 'C': 1.0, 'converged': True, 'iterations': 59, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold1_m0_C1.joblib'}]}
Completed 15/33: {'model_position': 5, 'seconds': 9.99924230016768, 'fits': [{'kind': 'linear', 'C': 1.0, 'converged': True, 'iterations': 22, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold1_m5_C1.joblib'}]}
Completed 16/33: {'model_position': 4, 'seconds': 15.10043069999665, 'fits': [{'kind': 'linear', 'C': 1.0, 'converged': True, 'iterations': 35, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold1_m4_C1.joblib'}]}
Completed 17/33: {'model_position': 3, 'seconds': 19.657084099948406, 'fits': [{'kind': 'linear', 'C': 1.0, 'converged': True, 'iterations': 43, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold1_m3_C1.joblib'}]}
Completed 18/33: {'model_position': 8, 'seconds': 11.768227399792522, 'fits': [{'kind': 'linear', 'C': 1.0, 'converged': True, 'iterations': 33, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold1_m8_C1.joblib'}]}
Completed 19/33: {'model_position': 6, 'seconds': 16.41002559987828, 'fits': [{'kind': 'linear', 'C': 1.0, 'converged': True, 'iterations': 45, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold1_m6_C1.joblib'}]}
Completed 20/33: {'model_position': 7, 'seconds': 14.558884999714792, 'fits': [{'kind': 'linear', 'C': 1.0, 'converged': True, 'iterations': 43, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold1_m7_C1.joblib'}]}
Completed 21/33: {'model_position': 9, 'seconds': 17.444249299820513, 'fits': [{'kind': 'linear', 'C': 1.0, 'converged': True, 'iterations': 42, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold1_m9_C1.joblib'}]}
Completed 22/33: {'model_position': 10, 'seconds': 27.75285799987614, 'fits': [{'kind': 'linear', 'C': 1.0, 'converged': True, 'iterations': 62, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold1_m10_C1.joblib'}]}
Completed 23/33: {'model_position': 2, 'seconds': 15.760178099852055, 'fits': [{'kind': 'linear', 'C': 10.0, 'converged': True, 'iterations': 33, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold1_m2_C10.joblib'}]}
Completed 24/33: {'model_position': 1, 'seconds': 28.06500930013135, 'fits': [{'kind': 'linear', 'C': 10.0, 'converged': True, 'iterations': 56, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold1_m1_C10.joblib'}]}
Completed 25/33: {'model_position': 0, 'seconds': 43.337281399872154, 'fits': [{'kind': 'linear', 'C': 10.0, 'converged': True, 'iterations': 90, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold1_m0_C10.joblib'}]}
Completed 26/33: {'model_position': 4, 'seconds': 13.838261500000954, 'fits': [{'kind': 'linear', 'C': 10.0, 'converged': True, 'iterations': 43, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold1_m4_C10.joblib'}]}
Completed 27/33: {'model_position': 5, 'seconds': 19.741042100358754, 'fits': [{'kind': 'linear', 'C': 10.0, 'converged': True, 'iterations': 57, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold1_m5_C10.joblib'}]}
Completed 28/33: {'model_position': 3, 'seconds': 33.073700999841094, 'fits': [{'kind': 'linear', 'C': 10.0, 'converged': True, 'iterations': 96, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold1_m3_C10.joblib'}]}
Completed 29/33: {'model_position': 6, 'seconds': 22.494530799798667, 'fits': [{'kind': 'linear', 'C': 10.0, 'converged': True, 'iterations': 65, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold1_m6_C10.joblib'}]}
Completed 30/33: {'model_position': 7, 'seconds': 28.654706800356507, 'fits': [{'kind': 'linear', 'C': 10.0, 'converged': True, 'iterations': 85, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold1_m7_C10.joblib'}]}
Completed 31/33: {'model_position': 8, 'seconds': 28.31054659979418, 'fits': [{'kind': 'linear', 'C': 10.0, 'converged': True, 'iterations': 84, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold1_m8_C10.joblib'}]}
Completed 32/33: {'model_position': 9, 'seconds': 32.16182059980929, 'fits': [{'kind': 'linear', 'C': 10.0, 'converged': True, 'iterations': 109, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold1_m9_C10.joblib'}]}
Completed 33/33: {'model_position': 10, 'seconds': 22.663392200134695, 'fits': [{'kind': 'linear', 'C': 10.0, 'converged': True, 'iterations': 77, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold1_m10_C10.joblib'}]}
  C=0.1 / 1/11 / WizardLM/WizardLM-13B-V1.2: CE=0.7663, iterations=24, converged=True
  C=0.1 / 2/11 / claude-instant-v1: CE=0.7107, iterations=27, converged=True
  C=0.1 / 3/11 / claude-v1: CE=0.6834, iterations=25, converged=True
  C=0.1 / 4/11 / claude-v2: CE=0.6938, iterations=21, converged=True
  C=0.1 / 5/11 / gpt-3.5-turbo-1106: CE=0.7439, iterations=31, converged=True
  C=0.1 / 6/11 / gpt-4-1106-preview: CE=0.5534, iterations=16, converged=True
  C=0.1 / 7/11 / meta/code-llama-instruct-34b-chat: CE=0.5065, iterations=19, converged=True
  C=0.1 / 8/11 / meta/llama-2-70b-chat: CE=0.6032, iterations=20, converged=True
  C=0.1 / 9/11 / mistralai/mistral-7b-chat: CE=0.6855, iterations=20, converged=True
  C=0.1 / 10/11 / mistralai/mixtral-8x7b-chat: CE=0.7602, iterations=32, converged=True
  C=0.1 / 11/11 / zero-one-ai/Yi-34B-Chat: CE=0.6978, iterations=22, converged=True
  C=1 / 1/11 / WizardLM/WizardLM-13B-V1.2: CE=0.7530, iterations=59, converged=True
  C=1 / 2/11 / claude-instant-v1: CE=0.6950, iterations=34, converged=True
  C=1 / 3/11 / claude-v1: CE=0.6587, iterations=37, converged=True
  C=1 / 4/11 / claude-v2: CE=0.6727, iterations=43, converged=True
  C=1 / 5/11 / gpt-3.5-turbo-1106: CE=0.7217, iterations=35, converged=True
  C=1 / 6/11 / gpt-4-1106-preview: CE=0.5255, iterations=22, converged=True
  C=1 / 7/11 / meta/code-llama-instruct-34b-chat: CE=0.4619, iterations=45, converged=True
  C=1 / 8/11 / meta/llama-2-70b-chat: CE=0.5481, iterations=43, converged=True
  C=1 / 9/11 / mistralai/mistral-7b-chat: CE=0.6617, iterations=33, converged=True
  C=1 / 10/11 / mistralai/mixtral-8x7b-chat: CE=0.7297, iterations=42, converged=True
  C=1 / 11/11 / zero-one-ai/Yi-34B-Chat: CE=0.6694, iterations=62, converged=True
  C=10 / 1/11 / WizardLM/WizardLM-13B-V1.2: CE=0.9080, iterations=90, converged=True
  C=10 / 2/11 / claude-instant-v1: CE=0.8039, iterations=56, converged=True
  C=10 / 3/11 / claude-v1: CE=0.7043, iterations=33, converged=True
  C=10 / 4/11 / claude-v2: CE=0.7716, iterations=96, converged=True
  C=10 / 5/11 / gpt-3.5-turbo-1106: CE=0.8067, iterations=43, converged=True
  C=10 / 6/11 / gpt-4-1106-preview: CE=0.5846, iterations=57, converged=True
  C=10 / 7/11 / meta/code-llama-instruct-34b-chat: CE=0.5207, iterations=65, converged=True
  C=10 / 8/11 / meta/llama-2-70b-chat: CE=0.6246, iterations=85, converged=True
  C=10 / 9/11 / mistralai/mistral-7b-chat: CE=0.7890, iterations=84, converged=True
  C=10 / 10/11 / mistralai/mixtral-8x7b-chat: CE=0.8530, iterations=109, converged=True
  C=10 / 11/11 / zero-one-ai/Yi-34B-Chat: CE=0.7803, iterations=77, converged=True
Linear score CV / TF-IDF / fold 2: features
Parallel linear: 33 tasks, 3 processes
Completed 1/33: {'model_position': 1, 'seconds': 6.66649129986763, 'fits': [{'kind': 'linear', 'C': 0.1, 'converged': True, 'iterations': 22, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold2_m1_C0.1.joblib'}]}
Completed 2/33: {'model_position': 2, 'seconds': 6.888884000014514, 'fits': [{'kind': 'linear', 'C': 0.1, 'converged': True, 'iterations': 21, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold2_m2_C0.1.joblib'}]}
Completed 3/33: {'model_position': 0, 'seconds': 7.157217000145465, 'fits': [{'kind': 'linear', 'C': 0.1, 'converged': True, 'iterations': 23, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold2_m0_C0.1.joblib'}]}
Completed 4/33: {'model_position': 5, 'seconds': 5.789156700018793, 'fits': [{'kind': 'linear', 'C': 0.1, 'converged': True, 'iterations': 17, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold2_m5_C0.1.joblib'}]}
Completed 5/33: {'model_position': 3, 'seconds': 6.320922200102359, 'fits': [{'kind': 'linear', 'C': 0.1, 'converged': True, 'iterations': 20, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold2_m3_C0.1.joblib'}]}
Completed 6/33: {'model_position': 4, 'seconds': 9.044033800251782, 'fits': [{'kind': 'linear', 'C': 0.1, 'converged': True, 'iterations': 28, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold2_m4_C0.1.joblib'}]}
Completed 7/33: {'model_position': 6, 'seconds': 4.649830600246787, 'fits': [{'kind': 'linear', 'C': 0.1, 'converged': True, 'iterations': 15, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold2_m6_C0.1.joblib'}]}
Completed 8/33: {'model_position': 7, 'seconds': 9.558862700127065, 'fits': [{'kind': 'linear', 'C': 0.1, 'converged': True, 'iterations': 28, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold2_m7_C0.1.joblib'}]}
Completed 9/33: {'model_position': 8, 'seconds': 6.892825799994171, 'fits': [{'kind': 'linear', 'C': 0.1, 'converged': True, 'iterations': 20, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold2_m8_C0.1.joblib'}]}
Completed 10/33: {'model_position': 9, 'seconds': 9.423599899746478, 'fits': [{'kind': 'linear', 'C': 0.1, 'converged': True, 'iterations': 23, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold2_m9_C0.1.joblib'}]}
Completed 11/33: {'model_position': 10, 'seconds': 10.458895899821073, 'fits': [{'kind': 'linear', 'C': 0.1, 'converged': True, 'iterations': 22, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold2_m10_C0.1.joblib'}]}
Completed 12/33: {'model_position': 1, 'seconds': 13.425297699868679, 'fits': [{'kind': 'linear', 'C': 1.0, 'converged': True, 'iterations': 34, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold2_m1_C1.joblib'}]}
Completed 13/33: {'model_position': 0, 'seconds': 21.105622299946845, 'fits': [{'kind': 'linear', 'C': 1.0, 'converged': True, 'iterations': 53, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold2_m0_C1.joblib'}]}

  Feature     C  ...  Max_observed_classes     Seconds
0   tfidf   0.1  ...                     5  604.002780
1   tfidf   1.0  ...                     5    2.178599
2   tfidf  10.0  ...                     5    2.161826
3  e5_388   0.1  ...                     5  104.429894
4  e5_388   1.0  ...                     5    0.623219
5  e5_388  10.0  ...                     5    0.640777

[6 rows x 9 columns]

Selected score-classifier C: {'tfidf': 1.0, 'e5_388': 1.0}

In [8]:
linear_models = {}
linear_fit_rows = []
for feature in feature_labels:
    C = selected_linear_C[feature]
    X_train = split_features[feature]["train"]
    heads = []
    for model_position, model_name in enumerate(model_names):
        started = perf_counter()
        head = fit_linear_score_head(X_train, score_class_ids[:, model_position], C)
        heads.append(head)
        linear_fit_rows.append({
            "Feature": feature, "Model": model_name, "C": C,
            "Iterations": head["iterations"], "Converged": head["converged"],
            "Convergence_warnings": head["convergence_warning_count"],
            "Observed_classes": len(head["observed_classes"]),
            "Seconds": perf_counter() - started,
        })
        print(f"Logistic / {feature_labels[feature]} / {model_position + 1}/{len(model_names)}: {model_name}")

    cost_model = Ridge(
        alpha=COST_RIDGE_ALPHA[feature], solver="lsqr", tol=1e-3, max_iter=1000,
    ).fit(X_train, train_cost_normalized)
    linear_models[feature] = {"heads": heads, "cost_model": cost_model, "selected_C": C}
    for split in ("calibration", "validation"):
        X = split_features[feature][split]
        probabilities = np.stack([linear_score_probabilities(head, X) for head in heads], axis=1)
        costs = np.maximum(cost_model.predict(X), 1e-6) * cost_means[None, :]
        prediction_bundles[("L2 logistic", feature, split)] = {
            "probability": probabilities, "cost": prediction_frame(costs, split),
        }

linear_fit_table = pd.DataFrame(linear_fit_rows)
display(linear_fit_table)
if (~linear_fit_table["Converged"]).any():
    warnings.warn("Some final classifiers did not converge; check the fit diagnostics.")

Parallel linear: 11 tasks, 3 processes
Completed 1/11: {'model_position': 2, 'seconds': 19.158276699949056, 'fits': [{'kind': 'linear', 'C': 1.0, 'converged': True, 'iterations': 38, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold0_m2_C1.joblib'}]}
Completed 2/11: {'model_position': 0, 'seconds': 21.21010740008205, 'fits': [{'kind': 'linear', 'C': 1.0, 'converged': True, 'iterations': 41, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold0_m0_C1.joblib'}]}
Completed 3/11: {'model_position': 1, 'seconds': 30.42770090000704, 'fits': [{'kind': 'linear', 'C': 1.0, 'converged': True, 'iterations': 64, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold0_m1_C1.joblib'}]}
Completed 4/11: {'model_position': 3, 'seconds': 22.16266839997843, 'fits': [{'kind': 'linear', 'C': 1.0, 'converged': True, 'iterations': 42, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold0_m3_C1.joblib'}]}
Completed 5/11: {'model_position': 4, 'seconds': 20.946397100109607, 'fits': [{'kind': 'linear', 'C': 1.0, 'converged': True, 'iterations': 39, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold0_m4_C1.joblib'}]}
Completed 6/11: {'model_position': 5, 'seconds': 20.735185800120234, 'fits': [{'kind': 'linear', 'C': 1.0, 'converged': True, 'iterations': 36, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold0_m5_C1.joblib'}]}
Completed 7/11: {'model_position': 6, 'seconds': 22.647981599904597, 'fits': [{'kind': 'linear', 'C': 1.0, 'converged': True, 'iterations': 49, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold0_m6_C1.joblib'}]}
Completed 8/11: {'model_position': 8, 'seconds': 18.747537899762392, 'fits': [{'kind': 'linear', 'C': 1.0, 'converged': True, 'iterations': 41, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold0_m8_C1.joblib'}]}
Completed 9/11: {'model_position': 7, 'seconds': 29.050518999807537, 'fits': [{'kind': 'linear', 'C': 1.0, 'converged': True, 'iterations': 64, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold0_m7_C1.joblib'}]}
Completed 10/11: {'model_position': 9, 'seconds': 17.998528100084513, 'fits': [{'kind': 'linear', 'C': 1.0, 'converged': True, 'iterations': 43, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold0_m9_C1.joblib'}]}
Completed 11/11: {'model_position': 10, 'seconds': 15.103260799776763, 'fits': [{'kind': 'linear', 'C': 1.0, 'converged': True, 'iterations': 43, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_tfidf_fold0_m10_C1.joblib'}]}
Logistic / TF-IDF / 1/11: WizardLM/WizardLM-13B-V1.2
Logistic / TF-IDF / 2/11: claude-instant-v1
Logistic / TF-IDF / 3/11: claude-v1
Logistic / TF-IDF / 4/11: claude-v2
Logistic / TF-IDF / 5/11: gpt-3.5-turbo-1106
Logistic / TF-IDF / 6/11: gpt-4-1106-preview
Logistic / TF-IDF / 7/11: meta/code-llama-instruct-34b-chat
Logistic / TF-IDF / 8/11: meta/llama-2-70b-chat
Logistic / TF-IDF / 9/11: mistralai/mistral-7b-chat
Logistic / TF-IDF / 10/11: mistralai/mixtral-8x7b-chat
Logistic / TF-IDF / 11/11: zero-one-ai/Yi-34B-Chat
Parallel linear: 11 tasks, 3 processes
Completed 1/11: {'model_position': 2, 'seconds': 3.8006210001185536, 'fits': [{'kind': 'linear', 'C': 1.0, 'converged': True, 'iterations': 70, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_e5_388_fold0_m2_C1.joblib'}]}
Completed 2/11: {'model_position': 0, 'seconds': 3.9111537002027035, 'fits': [{'kind': 'linear', 'C': 1.0, 'converged': True, 'iterations': 78, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_e5_388_fold0_m0_C1.joblib'}]}
Completed 3/11: {'model_position': 1, 'seconds': 4.863501199986786, 'fits': [{'kind': 'linear', 'C': 1.0, 'converged': True, 'iterations': 90, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_e5_388_fold0_m1_C1.joblib'}]}
Completed 4/11: {'model_position': 3, 'seconds': 2.922814800404012, 'fits': [{'kind': 'linear', 'C': 1.0, 'converged': True, 'iterations': 49, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_e5_388_fold0_m3_C1.joblib'}]}
Completed 5/11: {'model_position': 4, 'seconds': 3.9897929998114705, 'fits': [{'kind': 'linear', 'C': 1.0, 'converged': True, 'iterations': 72, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_e5_388_fold0_m4_C1.joblib'}]}
Completed 6/11: {'model_position': 5, 'seconds': 4.251653099898249, 'fits': [{'kind': 'linear', 'C': 1.0, 'converged': True, 'iterations': 72, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_e5_388_fold0_m5_C1.joblib'}]}
Completed 7/11: {'model_position': 6, 'seconds': 4.269165600184351, 'fits': [{'kind': 'linear', 'C': 1.0, 'converged': True, 'iterations': 66, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_e5_388_fold0_m6_C1.joblib'}]}
Completed 8/11: {'model_position': 7, 'seconds': 3.9052741997875273, 'fits': [{'kind': 'linear', 'C': 1.0, 'converged': True, 'iterations': 58, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_e5_388_fold0_m7_C1.joblib'}]}
Completed 9/11: {'model_position': 8, 'seconds': 3.4911921001039445, 'fits': [{'kind': 'linear', 'C': 1.0, 'converged': True, 'iterations': 51, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_e5_388_fold0_m8_C1.joblib'}]}
Completed 10/11: {'model_position': 9, 'seconds': 4.5728265000507236, 'fits': [{'kind': 'linear', 'C': 1.0, 'converged': True, 'iterations': 94, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_e5_388_fold0_m9_C1.joblib'}]}
Completed 11/11: {'model_position': 10, 'seconds': 4.456642699893564, 'fits': [{'kind': 'linear', 'C': 1.0, 'converged': True, 'iterations': 98, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_linear_e5_388_fold0_m10_C1.joblib'}]}
Logistic / E5 + features (388) / 1/11: WizardLM/WizardLM-13B-V1.2
Logistic / E5 + features (388) / 2/11: claude-instant-v1
Logistic / E5 + features (388) / 3/11: claude-v1
Logistic / E5 + features (388) / 4/11: claude-v2
Logistic / E5 + features (388) / 5/11: gpt-3.5-turbo-1106
Logistic / E5 + features (388) / 6/11: gpt-4-1106-preview
Logistic / E5 + features (388) / 7/11: meta/code-llama-instruct-34b-chat
Logistic / E5 + features (388) / 8/11: meta/llama-2-70b-chat
Logistic / E5 + features (388) / 9/11: mistralai/mistral-7b-chat
Logistic / E5 + features (388) / 10/11: mistralai/mixtral-8x7b-chat
Logistic / E5 + features (388) / 11/11: zero-one-ai/Yi-34B-Chat

   Feature                              Model  ...  Observed_classes    Seconds
0    tfidf         WizardLM/WizardLM-13B-V1.2  ...                 5  91.418612
1    tfidf                  claude-instant-v1  ...                 5   0.002589
2    tfidf                          claude-v1  ...                 5   0.003512
3    tfidf                          claude-v2  ...                 5   0.003430
4    tfidf                 gpt-3.5-turbo-1106  ...                 5   0.002869
5    tfidf                 gpt-4-1106-preview  ...                 5   0.003094
6    tfidf  meta/code-llama-instruct-34b-chat  ...                 5   0.002685
7    tfidf              meta/llama-2-70b-chat  ...                 5   0.002384
8    tfidf          mistralai/mistral-7b-chat  ...                 5   0.001929
9    tfidf        mistralai/mixtral-8x7b-chat  ...                 5   0.002096
10   tfidf            zero-one-ai/Yi-34B-Chat  ...                 5   0.002239
11  e5_388         WizardLM/WizardLM-13B-V1.2  ...                 5  21.557757
12  e5_388                  claude-instant-v1  ...                 5   0.000654
13  e5_388                          claude-v1  ...                 5   0.000625
14  e5_388                          claude-v2  ...                 5   0.000775
15  e5_388                 gpt-3.5-turbo-1106  ...                 5   0.001873
16  e5_388                 gpt-4-1106-preview  ...                 5   0.001365
17  e5_388  meta/code-llama-instruct-34b-chat  ...                 5   0.001155
18  e5_388              meta/llama-2-70b-chat  ...                 5   0.001346
19  e5_388          mistralai/mistral-7b-chat  ...                 5   0.001064
20  e5_388        mistralai/mixtral-8x7b-chat  ...                 5   0.001172
21  e5_388            zero-one-ai/Yi-34B-Chat  ...                 5   0.001318

[22 rows x 8 columns]

Read the cross-validation and convergence tables before interpreting validation
differences. A selected `C` at either end of the grid suggests exploring a wider
grid in a later experiment. The price penalty is fixed separately for each
feature set. Only the score classifier's `C` is tuned in this notebook.

## 5. kNN class frequencies and mean dollar cost

Retrieve training neighbors with cosine distance:

$$d(x,x')=1-\frac{x^\mathsf T x'}{\|x\|\|x'\|}.$$

For $K$ neighbors, count their **mapped** score classes for each candidate LLM:

$$p_{mj}(q)=\frac1K\sum_{i\in N_K(q)}\mathbf1[z(s_{im})=j],
\qquad
\hat c_m(q)=\frac1K\sum_{i\in N_K(q)}c_{im}.$$

Expected score is the average of the mapped neighbor scores. Hard class is the
most frequent mapped score. Price remains the mean of the recorded neighbor
costs. Query in batches, reuse the same neighbors for every requested $K$, and
use `DISPLAY_K=40` in the main comparison. Keep all $K$ results in a separate table.

In [9]:
def predict_neighbor_classes(index, features, split):
    count = features.shape[0]
    n_classes = len(score_support)
    predictions = {
        k: {"probability": np.empty((count, len(model_names), n_classes)),
            "cost": np.empty((count, len(model_names)))}
        for k in K_VALUES
    }
    train_cost_values = train_costs.to_numpy(dtype=float)
    started = perf_counter()
    for start in range(0, count, QUERY_BATCH_SIZE):
        stop = min(start + QUERY_BATCH_SIZE, count)
        neighbors = index.kneighbors(
            features[start:stop], n_neighbors=max(K_VALUES), return_distance=False,
        )
        labels = score_class_ids[neighbors]
        cost_sums = np.cumsum(train_cost_values[neighbors], axis=1)
        class_counts = np.zeros((stop - start, len(model_names), n_classes))
        rows, models = np.indices((stop - start, len(model_names)))
        for position in range(max(K_VALUES)):
            class_counts[rows, models, labels[:, position, :]] += 1
            k = position + 1
            if k in predictions:
                predictions[k]["probability"][start:stop] = class_counts / k
                predictions[k]["cost"][start:stop] = cost_sums[:, position, :] / k
        print(f"kNN / {split}: {stop}/{count} questions | {perf_counter() - started:.1f}s", flush=True)
    for bundle in predictions.values():
        bundle["cost"] = prediction_frame(bundle["cost"], split)
    return predictions

In [10]:
knn_indices, knn_class_predictions = {}, {}
for feature in feature_labels:
    index = NearestNeighbors(metric="cosine", algorithm="brute", n_jobs=-1).fit(
        split_features[feature]["train"],
    )
    knn_indices[feature] = index
    knn_class_predictions[feature] = {}
    for split in ("calibration", "validation"):
        all_k = predict_neighbor_classes(index, split_features[feature][split], split)
        knn_class_predictions[feature][split] = all_k
        prediction_bundles[("kNN", feature, split)] = all_k[DISPLAY_K]

kNN / calibration: 128/3648 questions | 0.7s
kNN / calibration: 256/3648 questions | 1.5s
kNN / calibration: 384/3648 questions | 2.7s
kNN / calibration: 512/3648 questions | 4.2s
kNN / calibration: 640/3648 questions | 5.7s
kNN / calibration: 768/3648 questions | 7.2s
kNN / calibration: 896/3648 questions | 8.7s
kNN / calibration: 1024/3648 questions | 10.2s
kNN / calibration: 1152/3648 questions | 11.3s
kNN / calibration: 1280/3648 questions | 12.3s
kNN / calibration: 1408/3648 questions | 13.6s
kNN / calibration: 1536/3648 questions | 14.9s
kNN / calibration: 1664/3648 questions | 16.2s
kNN / calibration: 1792/3648 questions | 17.5s
kNN / calibration: 1920/3648 questions | 18.8s
kNN / calibration: 2048/3648 questions | 20.0s
kNN / calibration: 2176/3648 questions | 21.0s
kNN / calibration: 2304/3648 questions | 22.1s
kNN / calibration: 2432/3648 questions | 23.1s
kNN / calibration: 2560/3648 questions | 24.1s
kNN / calibration: 2688/3648 questions | 25.2s
kNN / calibration: 2816/3648 questions | 26.4s
kNN / calibration: 2944/3648 questions | 27.6s
kNN / calibration: 3072/3648 questions | 28.7s
kNN / calibration: 3200/3648 questions | 29.8s
kNN / calibration: 3328/3648 questions | 31.2s
kNN / calibration: 3456/3648 questions | 32.4s
kNN / calibration: 3584/3648 questions | 33.4s
kNN / calibration: 3648/3648 questions | 34.1s
kNN / validation: 128/3649 questions | 1.0s
kNN / validation: 256/3649 questions | 1.9s
kNN / validation: 384/3649 questions | 3.0s
kNN / validation: 512/3649 questions | 4.6s
kNN / validation: 640/3649 questions | 6.0s
kNN / validation: 768/3649 questions | 7.5s
kNN / validation: 896/3649 questions | 9.0s
kNN / validation: 1024/3649 questions | 10.5s
kNN / validation: 1152/3649 questions | 11.6s
kNN / validation: 1280/3649 questions | 12.8s
kNN / validation: 1408/3649 questions | 14.0s
kNN / validation: 1536/3649 questions | 15.3s
kNN / validation: 1664/3649 questions | 16.6s
kNN / validation: 1792/3649 questions | 18.0s
kNN / validation: 1920/3649 questions | 19.3s
kNN / validation: 2048/3649 questions | 20.6s
kNN / validation: 2176/3649 questions | 21.6s
kNN / validation: 2304/3649 questions | 22.6s
kNN / validation: 2432/3649 questions | 23.6s
kNN / validation: 2560/3649 questions | 24.7s
kNN / validation: 2688/3649 questions | 25.8s
kNN / validation: 2816/3649 questions | 27.0s
kNN / validation: 2944/3649 questions | 28.0s
kNN / validation: 3072/3649 questions | 29.1s
kNN / validation: 3200/3649 questions | 30.3s
kNN / validation: 3328/3649 questions | 31.6s
kNN / validation: 3456/3649 questions | 32.8s
kNN / validation: 3584/3649 questions | 33.8s
kNN / validation: 3649/3649 questions | 34.4s
kNN / calibration: 128/3648 questions | 0.1s
kNN / calibration: 256/3648 questions | 0.3s
kNN / calibration: 384/3648 questions | 0.4s
kNN / calibration: 512/3648 questions | 0.5s
kNN / calibration: 640/3648 questions | 0.6s
kNN / calibration: 768/3648 questions | 0.7s
kNN / calibration: 896/3648 questions | 0.8s
kNN / calibration: 1024/3648 questions | 0.9s
kNN / calibration: 1152/3648 questions | 1.0s
kNN / calibration: 1280/3648 questions | 1.1s
kNN / calibration: 1408/3648 questions | 1.3s
kNN / calibration: 1536/3648 questions | 1.4s
kNN / calibration: 1664/3648 questions | 1.5s
kNN / calibration: 1792/3648 questions | 1.6s
kNN / calibration: 1920/3648 questions | 1.7s
kNN / calibration: 2048/3648 questions | 1.8s
kNN / calibration: 2176/3648 questions | 1.9s
kNN / calibration: 2304/3648 questions | 2.0s
kNN / calibration: 2432/3648 questions | 2.1s
kNN / calibration: 2560/3648 questions | 2.2s
kNN / calibration: 2688/3648 questions | 2.3s
kNN / calibration: 2816/3648 questions | 2.4s
kNN / calibration: 2944/3648 questions | 2.5s
kNN / calibration: 3072/3648 questions | 2.6s
kNN / calibration: 3200/3648 questions | 2.7s
kNN / calibration: 3328/3648 questions | 2.8s
kNN / calibration: 3456/3648 questions | 2.9s
kNN / calibration: 3584/3648 questions | 3.0s
kNN / calibration: 3648/3648 questions | 3.0s
kNN / validation: 128/3649 questions | 0.1s
kNN / validation: 256/3649 questions | 0.2s
kNN / validation: 384/3649 questions | 0.3s
kNN / validation: 512/3649 questions | 0.4s
kNN / validation: 640/3649 questions | 0.4s
kNN / validation: 768/3649 questions | 0.5s
kNN / validation: 896/3649 questions | 0.6s
kNN / validation: 1024/3649 questions | 0.7s
kNN / validation: 1152/3649 questions | 0.8s
kNN / validation: 1280/3649 questions | 0.9s
kNN / validation: 1408/3649 questions | 1.0s
kNN / validation: 1536/3649 questions | 1.1s
kNN / validation: 1664/3649 questions | 1.2s
kNN / validation: 1792/3649 questions | 1.3s
kNN / validation: 1920/3649 questions | 1.4s
kNN / validation: 2048/3649 questions | 1.5s
kNN / validation: 2176/3649 questions | 1.6s
kNN / validation: 2304/3649 questions | 1.7s
kNN / validation: 2432/3649 questions | 1.8s
kNN / validation: 2560/3649 questions | 1.9s
kNN / validation: 2688/3649 questions | 2.0s
kNN / validation: 2816/3649 questions | 2.1s
kNN / validation: 2944/3649 questions | 2.2s
kNN / validation: 3072/3649 questions | 2.3s
kNN / validation: 3200/3649 questions | 2.4s
kNN / validation: 3328/3649 questions | 2.5s
kNN / validation: 3456/3649 questions | 2.6s
kNN / validation: 3584/3649 questions | 2.7s
kNN / validation: 3649/3649 questions | 2.7s

## 6. XGBoost score classification and price prediction

Fit one boosted-tree score classifier and one price model per LLM. The score
head uses multiclass cross-entropy (`multi:softprob`). If a training subset has
only two observed classes, it uses binary cross-entropy. A constant target
produces a constant distribution. In every case, align the output to the same
five class columns and fill unobserved classes with zero probability.

The price head minimizes squared error on normalized costs. Restore dollar
units with the training cost means. Both hard and expected score outputs share
these price predictions. Tree settings are fixed in this experiment; XGBoost
hyperparameters are not selected by cross-validation here.

In [11]:
xgb_params = {
    "n_estimators": XGB_ROUNDS, "max_depth": 3, "learning_rate": 0.05,
    "subsample": 0.8, "colsample_bytree": 0.8, "max_bin": 64,
    "tree_method": "hist", "device": XGB_DEVICE, "n_jobs": XGB_N_JOBS,
    "reg_lambda": 1.0, "random_state": SEED,
}


def fit_xgb_score_head(features, targets):
    classes, encoded = np.unique(targets, return_inverse=True)
    if len(classes) == 1:
        return {"classifier": None, "classes": classes}
    objective = "binary:logistic" if len(classes) == 2 else "multi:softprob"
    options = {"eval_metric": "logloss" if len(classes) == 2 else "mlogloss"}
    if len(classes) > 2:
        options["num_class"] = len(classes)
    classifier = XGBClassifier(objective=objective, **options, **xgb_params).fit(features, encoded)
    actual_device = json.loads(classifier.get_booster().save_config())["learner"]["generic_param"]["device"]
    if XGB_DEVICE == "cuda" and not actual_device.startswith("cuda"):
        raise RuntimeError("XGBoost fell back to CPU. Set XGB_DEVICE='cpu' or check the GPU installation.")
    return {"classifier": classifier, "classes": classes}


def xgb_score_probabilities(head, features):
    if head["classifier"] is None:
        probabilities = np.zeros((features.shape[0], len(score_support)))
        probabilities[:, head["classes"][0]] = 1.0
        return probabilities
    return align_class_probabilities(head["classifier"].predict_proba(features), head["classes"], len(score_support))

In [12]:
xgb_models = {}
for feature in feature_labels:
    X_train = split_features[feature]["train"]
    xgb_models[feature] = {"score_classifier": [], "cost_regressor": []}
    raw = {split: {"probability": [], "cost": []} for split in ("calibration", "validation")}
    for model_position, model_name in enumerate(model_names):
        started = perf_counter()
        print(f"XGBoost / {feature_labels[feature]} / {model_position + 1}/{len(model_names)}: {model_name}", flush=True)
        head = fit_xgb_score_head(X_train, score_class_ids[:, model_position])
        price_head = XGBRegressor(objective="reg:squarederror", **xgb_params).fit(
            X_train, train_cost_normalized[:, model_position],
        )
        xgb_models[feature]["score_classifier"].append(head)
        xgb_models[feature]["cost_regressor"].append(price_head)
        for split in raw:
            X = split_features[feature][split]
            raw[split]["probability"].append(xgb_score_probabilities(head, X))
            costs = np.maximum(price_head.predict(X), 1e-6) * cost_means[model_position]
            raw[split]["cost"].append(costs)
        print(f"  completed in {perf_counter() - started:.1f}s", flush=True)
    for split, values in raw.items():
        prediction_bundles[("XGBoost", feature, split)] = {
            "probability": np.stack(values["probability"], axis=1),
            "cost": prediction_frame(np.column_stack(values["cost"]), split),
        }

XGBoost / TF-IDF / 1/11: WizardLM/WizardLM-13B-V1.2
Parallel xgb: 11 tasks, 2 processes
Completed 1/11: {'model_position': 1, 'seconds': 279.73125259997323, 'fits': [{'kind': 'score', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_score_tfidf_fold0_m1.joblib', 'seconds': 225.06367429997772}, {'kind': 'cost', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_cost_tfidf_fold0_m1.joblib', 'seconds': 54.62288610031828}]}
Completed 2/11: {'model_position': 0, 'seconds': 285.1203362001106, 'fits': [{'kind': 'score', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_score_tfidf_fold0_m0.joblib', 'seconds': 228.4007920003496}, {'kind': 'cost', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_cost_tfidf_fold0_m0.joblib', 'seconds': 56.67384049994871}]}
Completed 3/11: {'model_position': 2, 'seconds': 277.8668502001092, 'fits': [{'kind': 'score', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_score_tfidf_fold0_m2.joblib', 'seconds': 223.52285569999367}, {'kind': 'cost', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_cost_tfidf_fold0_m2.joblib', 'seconds': 54.32662779977545}]}
Completed 4/11: {'model_position': 3, 'seconds': 278.6944412998855, 'fits': [{'kind': 'score', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_score_tfidf_fold0_m3.joblib', 'seconds': 223.1305244998075}, {'kind': 'cost', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_cost_tfidf_fold0_m3.joblib', 'seconds': 55.54724179999903}]}
Completed 5/11: {'model_position': 4, 'seconds': 279.1128914002329, 'fits': [{'kind': 'score', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_score_tfidf_fold0_m4.joblib', 'seconds': 222.92334119975567}, {'kind': 'cost', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_cost_tfidf_fold0_m4.joblib', 'seconds': 56.17152900015935}]}
Completed 6/11: {'model_position': 5, 'seconds': 274.6878017997369, 'fits': [{'kind': 'score', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_score_tfidf_fold0_m5.joblib', 'seconds': 220.97182359965518}, {'kind': 'cost', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_cost_tfidf_fold0_m5.joblib', 'seconds': 53.704353800043464}]}
Completed 7/11: {'model_position': 6, 'seconds': 280.84538670023903, 'fits': [{'kind': 'score', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_score_tfidf_fold0_m6.joblib', 'seconds': 224.45671450020745}, {'kind': 'cost', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_cost_tfidf_fold0_m6.joblib', 'seconds': 56.37197300000116}]}
Completed 8/11: {'model_position': 7, 'seconds': 283.8263560999185, 'fits': [{'kind': 'score', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_score_tfidf_fold0_m7.joblib', 'seconds': 227.79578510019928}, {'kind': 'cost', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_cost_tfidf_fold0_m7.joblib', 'seconds': 56.01684490032494}]}
Completed 9/11: {'model_position': 8, 'seconds': 275.75237079989165, 'fits': [{'kind': 'score', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_score_tfidf_fold0_m8.joblib', 'seconds': 224.19737900001928}, {'kind': 'cost', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_cost_tfidf_fold0_m8.joblib', 'seconds': 51.53525949968025}]}
Completed 10/11: {'model_position': 9, 'seconds': 296.61384419957176, 'fits': [{'kind': 'score', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_score_tfidf_fold0_m9.joblib', 'seconds': 237.41804319992661}, {'kind': 'cost', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_cost_tfidf_fold0_m9.joblib', 'seconds': 59.179774299729615}]}
Completed 11/11: {'model_position': 10, 'seconds': 201.4678564001806, 'fits': [{'kind': 'score', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_score_tfidf_fold0_m10.joblib', 'seconds': 163.43551019998267}, {'kind': 'cost', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_cost_tfidf_fold0_m10.joblib', 'seconds': 38.010260600131005}]}
  completed in 1599.5s
XGBoost / TF-IDF / 2/11: claude-instant-v1
  completed in 0.1s
XGBoost / TF-IDF / 3/11: claude-v1
  completed in 0.1s
XGBoost / TF-IDF / 4/11: claude-v2
  completed in 0.1s
XGBoost / TF-IDF / 5/11: gpt-3.5-turbo-1106
  completed in 0.2s
XGBoost / TF-IDF / 6/11: gpt-4-1106-preview
  completed in 0.2s
XGBoost / TF-IDF / 7/11: meta/code-llama-instruct-34b-chat
  completed in 0.2s
XGBoost / TF-IDF / 8/11: meta/llama-2-70b-chat
  completed in 0.2s
XGBoost / TF-IDF / 9/11: mistralai/mistral-7b-chat
  completed in 0.2s
XGBoost / TF-IDF / 10/11: mistralai/mixtral-8x7b-chat
  completed in 0.2s
XGBoost / TF-IDF / 11/11: zero-one-ai/Yi-34B-Chat
  completed in 0.2s
XGBoost / E5 + features (388) / 1/11: WizardLM/WizardLM-13B-V1.2
Parallel xgb: 11 tasks, 2 processes
Completed 1/11: {'model_position': 1, 'seconds': 16.964463700074703, 'fits': [{'kind': 'score', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_score_e5_388_fold0_m1.joblib', 'seconds': 13.440584199968725}, {'kind': 'cost', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_cost_e5_388_fold0_m1.joblib', 'seconds': 3.4781450000591576}]}
Completed 2/11: {'model_position': 0, 'seconds': 17.513203899841756, 'fits': [{'kind': 'score', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_score_e5_388_fold0_m0.joblib', 'seconds': 13.91454160027206}, {'kind': 'cost', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_cost_e5_388_fold0_m0.joblib', 'seconds': 3.554970500059426}]}
Completed 3/11: {'model_position': 2, 'seconds': 17.22046560002491, 'fits': [{'kind': 'score', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_score_e5_388_fold0_m2.joblib', 'seconds': 13.831634200178087}, {'kind': 'cost', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_cost_e5_388_fold0_m2.joblib', 'seconds': 3.373245000373572}]}
Completed 4/11: {'model_position': 3, 'seconds': 17.31008359976113, 'fits': [{'kind': 'score', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_score_e5_388_fold0_m3.joblib', 'seconds': 13.842197199817747}, {'kind': 'cost', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_cost_e5_388_fold0_m3.joblib', 'seconds': 3.456988099962473}]}
Completed 5/11: {'model_position': 4, 'seconds': 17.787270000204444, 'fits': [{'kind': 'score', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_score_e5_388_fold0_m4.joblib', 'seconds': 14.135056199971586}, {'kind': 'cost', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_cost_e5_388_fold0_m4.joblib', 'seconds': 3.6380052999593318}]}
Completed 6/11: {'model_position': 5, 'seconds': 17.1930741998367, 'fits': [{'kind': 'score', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_score_e5_388_fold0_m5.joblib', 'seconds': 13.814008499961346}, {'kind': 'cost', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_cost_e5_388_fold0_m5.joblib', 'seconds': 3.3636733000166714}]}
Completed 7/11: {'model_position': 6, 'seconds': 17.45556510007009, 'fits': [{'kind': 'score', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_score_e5_388_fold0_m6.joblib', 'seconds': 13.799519999884069}, {'kind': 'cost', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_cost_e5_388_fold0_m6.joblib', 'seconds': 3.644044500309974}]}
Completed 8/11: {'model_position': 7, 'seconds': 17.74641939997673, 'fits': [{'kind': 'score', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_score_e5_388_fold0_m7.joblib', 'seconds': 14.107832599896938}, {'kind': 'cost', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_cost_e5_388_fold0_m7.joblib', 'seconds': 3.6277959998697042}]}
Completed 9/11: {'model_position': 8, 'seconds': 17.672215499915183, 'fits': [{'kind': 'score', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_score_e5_388_fold0_m8.joblib', 'seconds': 13.89956729998812}, {'kind': 'cost', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_cost_e5_388_fold0_m8.joblib', 'seconds': 3.762703100219369}]}
Completed 10/11: {'model_position': 9, 'seconds': 17.74804149987176, 'fits': [{'kind': 'score', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_score_e5_388_fold0_m9.joblib', 'seconds': 13.949476500041783}, {'kind': 'cost', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_cost_e5_388_fold0_m9.joblib', 'seconds': 3.7834691000171006}]}
Completed 11/11: {'model_position': 10, 'seconds': 11.895959800109267, 'fits': [{'kind': 'score', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_score_e5_388_fold0_m10.joblib', 'seconds': 9.528922299854457}, {'kind': 'cost', 'cached': False, 'path': 'C:\\Users\\johnh\\MachineLearning\\project_erdos\\2_Router_Training\\experiment_outputs\\score_classification_5class\\full_seed42_20261013T080041_062763Z\\fit_checkpoints\\head_xgb_cost_e5_388_fold0_m10.joblib', 'seconds': 2.3503673998638988}]}
  completed in 104.0s
XGBoost / E5 + features (388) / 2/11: claude-instant-v1
  completed in 0.1s
XGBoost / E5 + features (388) / 3/11: claude-v1
  completed in 0.1s
XGBoost / E5 + features (388) / 4/11: claude-v2
  completed in 0.1s
XGBoost / E5 + features (388) / 5/11: gpt-3.5-turbo-1106
  completed in 0.1s
XGBoost / E5 + features (388) / 6/11: gpt-4-1106-preview
  completed in 0.1s
XGBoost / E5 + features (388) / 7/11: meta/code-llama-instruct-34b-chat
  completed in 0.1s
XGBoost / E5 + features (388) / 8/11: meta/llama-2-70b-chat
  completed in 0.1s
XGBoost / E5 + features (388) / 9/11: mistralai/mistral-7b-chat
  completed in 0.1s
XGBoost / E5 + features (388) / 10/11: mistralai/mixtral-8x7b-chat
  completed in 0.1s
XGBoost / E5 + features (388) / 11/11: zero-one-ai/Yi-34B-Chat
  completed in 0.1s

## 7. Evaluate probabilities and the two score outputs

For question $i$ and candidate LLM $m$:

$$\hat s^{\mathrm{hard}}_{im}=a_{\arg\max_j p_{imj}},
\qquad \hat s^{\mathrm{expected}}_{im}=\sum_{j=0}^4 a_jp_{imj}.$$

Hard class belongs to the five anchors. Expected score can take an intermediate
value, such as 0.63. An exact probability tie uses the lower anchor because the
class columns are ordered from 0 to 1.

**Probability metrics** evaluate the five-class target $z_{im}$:

$$\mathrm{Accuracy}_m=\frac1n\sum_i
\mathbf1[\arg\max_j p_{imj}=z_{im}],
\qquad
\mathrm{NLL}_m=-\frac1n\sum_i\log\max(p_{im,z_{im}},10^{-12}).$$

Balanced accuracy averages recall across the classes present in validation.
It reveals performance hidden by frequent classes. Report the fraction of
zero true-class probabilities alongside NLL; the numerical floor keeps NLL
finite. Accuracy measures hard class decisions, while NLL evaluates the whole
distribution.

**Numerical error metrics** compare both score outputs with the original recorded
score $s_{im}$. Predicted costs are compared with recorded dollar costs $c_{im}$:

$$\mathrm{MSE}_m=\frac1n\sum_i(\hat y_{im}-y_{im})^2,
\qquad \mathrm{MAE}_m=\frac1n\sum_i|\hat y_{im}-y_{im}|,$$

$$\mathrm{WAPE}_m=
\frac{\sum_i|\hat y_{im}-y_{im}|}{\sum_i|y_{im}|}.$$

Compute each metric separately for each LLM, then average equally across the
11 LLMs. WAPE avoids dividing by each individual zero score; an all-zero target
column gives an undefined WAPE and is counted explicitly. Hard and expected
outputs share price predictions, so their cost errors are identical.

In [13]:
NLL_EPSILON = 1e-12
score_support = np.asarray(score_support, dtype=float)
assert np.all(np.diff(score_support) > 0), "The score support must be strictly sorted."
validation_index = validation_scores.index
assert validation_costs.index.equals(validation_index), "Validation score/cost rows must align."
validation_truth = validation_scores.loc[:, model_names].to_numpy(dtype=float)
validation_cost_truth = validation_costs.loc[:, model_names].to_numpy(dtype=float)
n_questions, n_models = validation_truth.shape
n_score_classes = len(score_support)


validation_class_ids = encode_score_classes(validation_truth)


def checked_probability_bundle(bundle):
    probabilities = np.asarray(bundle["probability"], dtype=float)
    costs = bundle["cost"]
    if probabilities.shape != (n_questions, n_models, n_score_classes):
        raise ValueError("Probabilities must have shape (questions, candidate LLMs, classes).")
    if not np.isfinite(probabilities).all() or np.any(probabilities < 0):
        raise ValueError("Class probabilities must be finite and nonnegative.")
    if not np.allclose(probabilities.sum(axis=-1), 1.0, atol=1e-6):
        raise ValueError("Each candidate LLM needs a probability distribution summing to one.")
    if not costs.index.equals(validation_index) or costs.columns.tolist() != model_names:
        raise ValueError("Cost prediction rows and model columns must preserve validation order.")
    cost_values = costs.to_numpy(dtype=float)
    if not np.isfinite(cost_values).all() or np.any(cost_values < 0):
        raise ValueError("Predicted dollar costs must be finite and nonnegative.")
    return probabilities, cost_values


def distribution_metrics(bundle):
    probabilities, _ = checked_probability_bundle(bundle)
    hard_class_ids = probabilities.argmax(axis=-1)
    true_probabilities = np.take_along_axis(
        probabilities, validation_class_ids[..., None], axis=-1,
    )[..., 0]
    balanced_accuracy = []
    for model_position in range(n_models):
        truth = validation_class_ids[:, model_position]
        prediction = hard_class_ids[:, model_position]
        recalls = [(prediction[truth == value] == value).mean() for value in np.unique(truth)]
        balanced_accuracy.append(float(np.mean(recalls)))
    return pd.DataFrame({
        "Accuracy": (hard_class_ids == validation_class_ids).mean(axis=0),
        "Balanced_accuracy": balanced_accuracy,
        "NLL": -np.log(np.maximum(true_probabilities, NLL_EPSILON)).mean(axis=0),
        "Zero_true_probability_rate": (true_probabilities == 0).mean(axis=0),
    }, index=pd.Index(model_names, name="model"))


def score_outputs(bundle):
    probabilities, costs = checked_probability_bundle(bundle)
    expected_scores = probabilities @ score_support
    return {
        "Expected score": {"score": expected_scores, "cost": costs},
        "Hard class": {"score": score_support[probabilities.argmax(axis=-1)], "cost": costs},
    }


def relative_absolute_error(predictions, targets):
    totals = np.abs(targets).sum(axis=0)
    return np.divide(
        np.abs(predictions - targets).sum(axis=0), totals,
        out=np.full(targets.shape[1], np.nan), where=totals > 0,
    )


def numeric_prediction_metrics(bundle):
    scores, costs = bundle["score"], bundle["cost"]
    return pd.DataFrame({
        "Score_MSE": np.square(scores - validation_truth).mean(axis=0),
        "Score_MAE": np.abs(scores - validation_truth).mean(axis=0),
        "Score_WAPE": relative_absolute_error(scores, validation_truth),
        "Cost_MSE": np.square(costs - validation_cost_truth).mean(axis=0),
        "Cost_MAE": np.abs(costs - validation_cost_truth).mean(axis=0),
        "Cost_WAPE": relative_absolute_error(costs, validation_cost_truth),
    }, index=pd.Index(model_names, name="model"))


def training_frequency_bundle(train_scores, train_costs):
    train_values = train_scores.loc[:, model_names].to_numpy(dtype=float)
    train_classes = encode_score_classes(train_values)
    frequencies = np.stack([
        np.bincount(train_classes[:, model], minlength=n_score_classes) / len(train_values)
        for model in range(n_models)
    ])
    mean_costs = train_costs.loc[:, model_names].mean(axis=0).to_numpy(dtype=float)
    return {
        "probability": np.broadcast_to(frequencies, (n_questions, n_models, n_score_classes)),
        "cost": pd.DataFrame(np.broadcast_to(mean_costs, (n_questions, n_models)),
                             index=validation_index, columns=model_names),
    }

In [14]:
# prediction_bundles is keyed by (method, embedding, split).
validation_probability_bundles = {
    (method, embedding): bundle
    for (method, embedding, split), bundle in prediction_bundles.items()
    if split == "validation"
}
validation_probability_bundles = {
    ("Training frequency", "Baseline"): training_frequency_bundle(train_scores, train_costs),
    **validation_probability_bundles,
}
distribution_per_model = pd.concat({
    key: distribution_metrics(bundle)
    for key, bundle in validation_probability_bundles.items()
}, names=["method", "embedding"])
distribution_summary = distribution_per_model.groupby(
    level=["method", "embedding"], sort=False,
).mean()
numeric_validation_bundles = {
    (method, embedding, output): values
    for (method, embedding), bundle in validation_probability_bundles.items()
    for output, values in score_outputs(bundle).items()
}
numeric_per_model = pd.concat({
    key: numeric_prediction_metrics(bundle)
    for key, bundle in numeric_validation_bundles.items()
}, names=["method", "embedding", "score_output"])
numeric_summary = numeric_per_model.groupby(
    level=["method", "embedding", "score_output"], sort=False,
).mean()
for target in ("Score", "Cost"):
    numeric_summary[f"Defined_{target.lower()}_WAPE_models"] = numeric_per_model[
        f"{target}_WAPE"
    ].groupby(level=["method", "embedding", "score_output"], sort=False).count()

print("Validation probability quality: one result per trained classifier")
display(distribution_summary.style.format({
    "Accuracy": "{:.1%}", "Balanced_accuracy": "{:.1%}", "NLL": "{:.4f}",
    "Zero_true_probability_rate": "{:.1%}",
}))
print("Validation score/cost errors: two score outputs from the same probabilities")
display(numeric_summary.style.format({
    "Score_MSE": "{:.5f}", "Score_MAE": "{:.5f}", "Score_WAPE": "{:.1%}",
    "Cost_MSE": "{:.3e}", "Cost_MAE": "${:.8f}", "Cost_WAPE": "{:.1%}",
    "Defined_score_WAPE_models": "{:.0f}", "Defined_cost_WAPE_models": "{:.0f}",
}, na_rep="undefined"))
distribution_summary.to_csv(run_dir / "validation_classification_summary.csv")
distribution_per_model.to_csv(run_dir / "validation_classification_per_llm.csv")
numeric_summary.to_csv(run_dir / "validation_numeric_summary.csv")
numeric_per_model.to_csv(run_dir / "validation_numeric_per_llm.csv")

Validation probability quality: one result per trained classifier

Validation score/cost errors: two score outputs from the same probabilities

### Compare neighbor counts

The table below shows every requested `k` for both feature sets. Compare hard
and expected score errors within each `k`. Classification accuracy and NLL come
from their shared distribution, and cost errors come from their shared price
estimate. Keep validation comparisons exploratory when choosing a final `k`.

In [15]:
knn_grid_rows = []
for feature in feature_labels:
    for k in K_VALUES:
        bundle = knn_class_predictions[feature]["validation"][k]
        distribution = distribution_metrics(bundle)
        for output, scores in score_outputs(bundle).items():
            metrics = numeric_prediction_metrics(scores).mean()
            knn_grid_rows.append({"embedding": feature, "k": k, "output": output,
                                  "Score_WAPE": metrics["Score_WAPE"], "Cost_WAPE": metrics["Cost_WAPE"],
                                  "Score_MSE": metrics["Score_MSE"], "Score_MAE": metrics["Score_MAE"], "NLL": distribution["NLL"].mean(),
                                  "Accuracy": distribution["Accuracy"].mean()})
knn_grid_summary = pd.DataFrame(knn_grid_rows)
knn_grid_summary.to_csv(run_dir / "knn_score_classification_grid.csv", index=False)
display(knn_grid_summary.style.format({"Score_WAPE": "{:.1%}", "Cost_WAPE": "{:.1%}",
                                      "Score_MSE": "{:.5f}", "Score_MAE": "{:.5f}", "NLL": "{:.4f}", "Accuracy": "{:.1%}"}))

## 8. Save and reuse the results

Each run saves probability arrays, hard scores, expected scores and dollar costs
for calibration and validation. DataFrames preserve question indices and LLM
columns. Probability arrays use `(questions, 11 LLMs, 5 classes)`; the manifest
records both column orders. All kNN neighbor counts are exported, with `k=40`
also appearing in the main comparison.

The folder also contains metrics, class-coverage tables, training-fold records,
fit diagnostics, model settings and fitted Logistic/XGBoost objects. Saved
predictions can be loaded for further evaluation without fitting models again.
Prediction on new questions additionally requires the prepared TF-IDF/E5
workflow. kNN lookup objects can be rebuilt from the prepared training features
and mapped labels.

In [16]:
def save_prediction_bundle(prefix, bundle, split):
    probabilities = np.asarray(bundle["probability"], dtype=float)
    assert probabilities.shape == (len(tables[split]["questions"]), len(model_names), 5)
    assert np.isfinite(probabilities).all() and (probabilities >= 0).all()
    assert np.allclose(probabilities.sum(axis=-1), 1, atol=1e-6)
    np.save(run_dir / f"{prefix}_probability.npy", probabilities, allow_pickle=False)
    prediction_frame(probabilities @ score_support, split).to_pickle(run_dir / f"{prefix}_expected_score.pkl")
    prediction_frame(score_support[probabilities.argmax(axis=-1)], split).to_pickle(run_dir / f"{prefix}_hard_score.pkl")
    bundle["cost"].to_pickle(run_dir / f"{prefix}_dollar_cost.pkl")


prediction_manifest = []
for position, ((method, feature, split), bundle) in enumerate(prediction_bundles.items()):
    prefix = f"pred_{position:02d}_{split}"
    save_prediction_bundle(prefix, bundle, split)
    prediction_manifest.append({
        "prefix": prefix, "method": method, "embedding": feature, "split": split,
        "k": DISPLAY_K if method == "kNN" else None,
    })
pd.DataFrame(prediction_manifest).to_csv(run_dir / "predictions_manifest.csv", index=False)

knn_prediction_manifest = []
for feature, split_predictions in knn_class_predictions.items():
    for split, all_k in split_predictions.items():
        for k, bundle in all_k.items():
            prefix = f"knn_{feature}_k{k}_{split}"
            save_prediction_bundle(prefix, bundle, split)
            knn_prediction_manifest.append({
                "prefix": prefix, "embedding": feature, "split": split, "k": k,
            })
pd.DataFrame(knn_prediction_manifest).to_csv(run_dir / "knn_predictions_manifest.csv", index=False)

linear_cv_table.to_csv(run_dir / "linear_cv_folds.csv", index=False)
linear_cv_summary.to_csv(run_dir / "linear_cv_summary.csv", index=False)
linear_fit_table.to_csv(run_dir / "linear_final_fit.csv", index=False)
joblib.dump(linear_models, run_dir / "linear_models.joblib")
joblib.dump(xgb_models, run_dir / "xgb_models.joblib")

manifest = {
    "mode": RUN_MODE, "seed": SEED,
    "model_names": model_names, "score_support": score_support.tolist(),
    "label_mapping": "nearest fixed anchor; exact midpoint uses lower anchor",
    "numerical_score_metrics_target": "original recorded score",
    "training_cost_means": cost_means.tolist(),
    "selected_linear_C": selected_linear_C, "cost_ridge_alpha": COST_RIDGE_ALPHA,
    "xgb_parameters": xgb_params, "k_values": K_VALUES, "display_k": DISPLAY_K,
    "rows": {split: len(tables[split]["questions"]) for split in SPLITS},
    "test_used": False, "calibration_fitted": False,
    "versions": {"sklearn": sklearn.__version__, "xgboost": xgboost.__version__,
                 "numpy": np.__version__, "pandas": pd.__version__},
    "created_utc": datetime.now(timezone.utc).isoformat(),
}
(run_dir / "experiment_manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
print("Completed mode:", RUN_MODE)
print("Fixed score classes:", score_support.tolist())
print("Experiment outputs:", run_dir)
if RUN_MODE == "smoke":
    print("Smoke validates execution. Use full mode for performance comparisons.")

Completed mode: full
Fixed score classes: [0.0, 0.25, 0.5, 0.75, 1.0]
Experiment outputs: C:\Users\johnh\MachineLearning\project_erdos\2_Router_Training\experiment_outputs\score_classification_5class\full_seed42_20261013T080041_062763Z

## 9. Read the results

- Start with accuracy, balanced accuracy and NLL. A high accuracy combined with
  low balanced accuracy suggests weak performance on less frequent classes.
- Compare hard and expected outputs using raw-score MSE, MAE and WAPE. The
  outputs answer different questions: most likely category and average score.
- Compare TF-IDF and E5 using the same validation questions and metric definitions.
  Inspect the per-LLM CSV files when an average hides a weak candidate model.
- Use the training-frequency baseline to assess what the question features add.
- Verify `mode`, row counts and the class mapping in the saved manifest before
  interpreting an experiment. Smoke runs only check execution.

Further model selection and repeated validation comparisons can introduce
optimism. Reserve the untouched test split for the final selected experiment.

### Observations from the completed full run

This run uses all **21,900 train**, **3,648 calibration** and **3,649 validation**
questions. Training-only cross-validation selected **C = 1** for both feature
sets. All logistic fits converged. XGBoost used **100 boosting rounds** for every
score classifier and price model.

Five-class accuracy is about **68.0%?69.5%** across the six classifier/feature
combinations, compared with **53.8%** for the training-frequency baseline.
Hard class has lower raw-score MAE; expected score has lower raw-score MSE in
every combination. Read these metrics together because they measure different
errors. The two outputs share each method's price predictions.

**Execution note:** independent fits were computed in parallel and saved as
checkpoints during this run. Notebook loops then loaded the completed fits.
Their printed seconds include bulk precomputation or checkpoint loading; use
`fit_telemetry.csv` for the individual fit durations. Saved prediction tensors
have five class columns, and all requested kNN neighbor counts were exported.